STACKSEG SEGMENT PARA STACK 'STACK'
    DB 100 DUP(0)
STACKSEG ENDS

DATASEG1 SEGMENT PARA 'DATA'
    DB 100
    DB 0
    DB 101 DUP(0)
DATASEG1 ENDS

DATASEG2 SEGMENT PARA 'DATA'
    DB 2 DUP(0)
DATASEG2 ENDS

CODESEG SEGMENT PARA 'CODE'
    ASSUME CS:CODESEG, DS:DATASEG1, ES:DATASEG2, SS:STACKSEG
MAIN:
    MOV AX, DATASEG1
    MOV DS, AX

    MOV AH, 0AH
    MOV DX, 0
    INT 21H
    
    MOV DH, DS:3
    SUB DH, 48
    ADD DH, DS:6
    MOV ES:0, DH
    
    MOV AH, 2
    MOV DL, 13
    INT 21H
    MOV DL, 10
    INT 21H
    MOV DL, ES:0
    INT 21H
    
    MOV AH, 4CH
    INT 21H
CODESEG ENDS
END MAIN